### status

GET http://localhost:5000/status
Authorization: 'Bearer 123456'

### Boas vindas
GET http://localhost:5000/contas/1313-0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiYmI0NzFhNTgtYmFkZS00OWUxLTlhMzItNWU2MmQ0Y2MwNzY2IiwiZW1haWwiOiJmdWxhbm9AZW1haWwuY29tIiwiaWF0IjoxNzA2OTE5NTg4LCJleHAiOjE3MDY5MjMxODh9.Evd-iJtf5hrXEbTEUsUgPwAnLuoXIlW8xm77ALx6Jqo


### Saldo
GET http://localhost:5000/contas/1313-0/saldo


### Depósito DINHEIRO
POST http://localhost:5000/contas/1313-0/deposito
Content-Type: application/json

{
  "valor": 100,
  "tipo_deposito": "DINHEIRO"
}

### Login
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "fulano@email.com",
  "senha": "123456"
}