### status

GET http://localhost:5000/status
Authorization: 'Bearer 123456'

### Boas vindas
GET http://localhost:5000/contas/1313-0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiYmI0NzFhNTgtYmFkZS00OWUxLTlhMzItNWU2MmQ0Y2MwNzY2IiwiZW1haWwiOiJmdWxhbm9AZW1haWwuY29tIiwiaWF0IjoxNzA3MTcyNzU1LCJleHAiOjE3MDcxNzYzNTV9.fzQUC3SX0QOezK35s_ZRiyDU7W_5ddwahAOLtV1Qy04


### Saldo
GET http://localhost:5000/contas/1313-0/saldo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiYmI0NzFhNTgtYmFkZS00OWUxLTlhMzItNWU2MmQ0Y2MwNzY2IiwiZW1haWwiOiJmdWxhbm9AZW1haWwuY29tIiwiaWF0IjoxNzA3MTcyNzU1LCJleHAiOjE3MDcxNzYzNTV9.fzQUC3SX0QOezK35s_ZRiyDU7W_5ddwahAOLtV1Qy04

### Depósito DINHEIRO
POST http://localhost:5000/contas/1313-0/deposito
Content-Type: application/json

{
  "valor": 100,
  "tipo_deposito": "DINHEIRO"
}

### Login
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "fulano@email.com",
  "senha": "123456"
}


###login pessoa 

POST http://localhost:5000/pessoas/login
Content-Type: application/json

{
  "usuario":"eberton",
  "senha":"eberton"
}

###Cadastro pessoa 

POST http://localhost:5000/pessoas/cadastrar
Content-Type: application/json

{
  "nome_completo": "Eberton M. Alvares",
  "cpf":"123456789",
  "usuario":"eberton",
  "senha":"eberton"
}

###Atualizar dados pessoa
PATCH  http://localhost:5000/pessoas/265c4e5b-789c-45a8-8e28-cc55ddf16f79/atualizar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiYmI0NzFhNTgtYmFkZS00OWUxLTlhMzItNWU2MmQ0Y2MwNzY2IiwiZW1haWwiOiJmdWxhbm9AZW1haWwuY29tIiwiaWF0IjoxNzA3MzUzODgwLCJleHAiOjE3MDczNTc0ODB9.0WckSOTN9Vpe1bda7DiQiOo9chMC_AK-B73GwFHk-sA
{
  "nome_completo": "Eberton Alvares",
  "cpf":"12345678900",
  "usuario":"eberton",
  "senha":"eberton"
}